# Written by Professor Paul N. Hilfinger
# A simple-minded makefile that just calls the one in the outer source
# directory.

.PHONY: default clean check style

default: 
	$(MAKE) -C .. default

check:
	$(MAKE) -C .. check

clean:
	$(MAKE) -C .. clean

